/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Cover: typeof import('./src/components/Shared/Cover.vue')['default']
    DynamicLyric: typeof import('./src/components/Shared/DynamicLyric.vue')['default']
    FadeTransition: typeof import('./src/components/Shared/FadeTransition.vue')['default']
    Info: typeof import('./src/components/Shared/Info.vue')['default']
    Lyrics: typeof import('./src/components/Shared/Lyrics.vue')['default']
    NCollapseTransition: typeof import('naive-ui')['NCollapseTransition']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NextPlay: typeof import('./src/components/Shared/NextPlay.vue')['default']
    NImage: typeof import('naive-ui')['NImage']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NProgress: typeof import('naive-ui')['NProgress']
    NSpace: typeof import('naive-ui')['NSpace']
    NText: typeof import('naive-ui')['NText']
    NumberRoll: typeof import('./src/components/Shared/NumberRoll.vue')['default']
    Panel: typeof import('./src/components/Panel.vue')['default']
    Progress: typeof import('./src/components/Shared/Progress.vue')['default']
  }
}
